index.template = "templates/index.html"
pages.template = "templates/page.html"

[[source]]
name = "Projects"
path = "projects"

[[source]]
name = "Posts"
path = "posts"

[[source]]
name = "Notes / TIL"
path = "notes"
