name = "evuez"
home = "https://liftm.io"
author = "evuez"

[templates]
index = "templates/index.html"
pages = "templates/page.html"

[[source]]
name = "Posts"
path = "posts"

[[source]]
name = "Notes"
path = "notes"

[[source]]
name = "Projects"
path = "projects"

