name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Run a one-line script
      run: docker run -v $(pwd):/mnt/repo fedora /mnt/repo/.github/kiwi
